
(__defun 1- (a)
         (__- a 1))

(__defun * (a b)
         (__var acc 0)

         (__var i 0)
         (__while (__< i b)
	              (__setq acc (__+ acc a))
	              (__setq i (__+ i 1)))
         acc)

(__defun factorial-helper (n acc)
         (__unless (__= n 1)
	               (__setq acc (self (1- n) (* n acc))))
         acc)

(__defun factorial (n)
         (factorial-helper n 1))
(__var x 5)
(__var y (factorial x))
(print y)
