(print "Starting leak\n")
(var x ())

(defun lcons (a b)
  (lambda (f)
	(funcall f a b)))

(defun lcar (f)
  (funcall f (lambda (a b) a)))

(defun lcdr (f)
  (funcall f (lambda (a b) b)))

(while true

  ;; Test stack
  5
  ()
  (lambda () ())
  ;; Force conses to be popped
  (setq x (cons (cons () ()) ()))

  ;; Force objects to be popped
  (setq x (cons (cons 1 2) 3))

  ;; Force closures (objects) to be popped
  (setq x (lcons (lcons 1 2) 3)))
