

(defun 1+ (a)
  (+ a 1))

(defun 1- (a)
  (- a 1))

(defun factorial1 (f n)
  (if (> n 1)
	  (* n (f (1+ n)))
	  1))
(defun factorial2 (f n)
  (if (> n 1)
	  (* n (f (- n 2)))
	  1))

(defun fix2 (f1 f2 n)
  (var フン1 ())
  (var フン2 ())
  (setq フン1 ((defun dummy1 (n)
				 (f1 フン2 n))))
  (setq フン2 ((defun dummy2 (n)
				 (f2 フン1 n))))
  (フン1 n))

(defun factorial (n)
  (fix2 factorial1 factorial2 n))

(var x 5)
(var y (factorial x))
(print y)
