

(defun 1+ (a)
  (+ a 1))

(defun 1- (a)
  (- a 1))

(defun factorial1 (f n)
  (if (> n 1)
	  (* n (funcall f (1+ n)))
	  1))
(defun factorial2 (f n)
  (if (> n 1)
	  (* n (funcall f (- n 2)))
	  1))

(defun fix2 (f1 f2 n)
  (var フン1 ())
  (var フン2 ())
  (setq フン1 (lambda (n)
				(funcall f1 フン2 n)))
  (setq フン2 (lambda (n)
				(funcall f2 フン1 n)))
  (funcall フン1 n))

(defun factorial (n)
  (fix2 factorial1 factorial2 n))

(print (factorial 5))
